import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import TopBar from "@/components/layout/TopBar";
import SideBar from "@/components/layout/SideBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "LawyerMeet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "font-sans antialiased bg-gradient-to-b from-gray-950 via-gray-900 to-gray-950",
        fontSans.variable
      )}>
        <div className="flex max-lg:flex-col  text-gray-500 font-extralight ">
          <TopBar />
          <SideBar />
          <div className="flex-1 p-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
